### ISSUE TITLE
Instalador não funciona

### ISSUE THREAD

**Issue by michelpl** [GabrielDeveloper/tmdb_movies_magento#1]
@GabrielDeveloper, tentamos instalar o módulo conforme descrito no README, porém ao tentar instalar o Magento pelo browser, ele retornou erro 500.

Segue o log do Apache:
```
[Wed Apr 11 14:11:08.147142 2018] [:error] [pid 218] [client 172.17.0.1:45166] PHP Fatal error:  Uncaught Magento\\Framework\\Exception\\FileSystemException: The directory "/app/generated/code" cannot be deleted Warning!rmdir(/app/generated/code): Permission denied in /app/lib/internal/Magento/Framework/Filesystem/Driver/File.php:410\nStack trace:\n#0 /app/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(174): Magento\\Framework\\Filesystem\\Driver\\File->deleteDirectory('/app/generated/...')\n#1 /app/lib/internal/Magento/Framework/Code/GeneratedFiles.php(87): Magento\\Framework\\Filesystem\\Directory\\Write->delete('generated/code')\n#2 /app/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(110): Magento\\Framework\\Code\\GeneratedFiles->cleanGeneratedFiles()\n#3 /app/lib/internal/Magento/Framework/App/Bootstrap.php(208): Magento\\Framework\\App\\ObjectManagerFactory->create(Array)\n#4 /app/lib/internal/Magento/Framework/App/Bootstrap.php(123): Magento\\Framework\\App\\Bootstrap->__construct(Object(Magento\\Framework\\App\\ObjectManagerFactory), '/app', Array)\n#5 /app/index.php(36): Magento\\Framework\\App\\Boot in /app/lib/internal/Magento/Framework/Filesystem/Driver/File.php on line 410
```

Também achamos que você poderia melhorar a documentação, dizendo como utilizar o módulo e o que é possível fazer.

**Comment by GabrielDeveloper** [comment]
@michelpl , esse erro é de permissão, o próprio magento tem um artigo sugerindo as permissões para evitar este tipo de erro.  Segue os links: 

http://devdocs.magento.com/guides/v2.0/install-gde/trouble/tshoot_var-gen-perms.html
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-sys-perms-over.html

Quanto a documentação, estou adicionando mais detalhes.

**Comment by felipebool** [comment]
Oi, @GabrielDeveloper. Só tivemos problema de permissão com o seu módulo. Todos os outros que usamos e testamos não apresentaram este tipo de problema. : )

Nós estamos utilizando as imagens do https://hub.docker.com/r/thiagobarradas/magento2/, teste nelas e reproduza o erro. Mais precisamente, estamos utilizando a thiagobarradas/magento2:2.2.2-php7.0. Se não quiser usar o docker, passe pra gente o caminho das pedras pra fazer funcionar.

Aguardo troubleshooting! : D

**Comment by GabrielDeveloper** [comment]
Fala @felipebool , consegui reproduzir o erro, vi que esqueci de colocar 2 comandos para rodar na instalação do modulo, falha minha:

php bin/magento setup:upgrade
php bin/magento setup:di:compile

Pode testar novamente rodando esses comandos por favor?

**Comment by felipebool** [comment]
Show de bola, @GabrielDeveloper.
